default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: snacks_app_dev
test:
  <<: *default
  database: snacks_app_test